# Arguments for Nvidia-Docker
# all combination set in CUDA, cuDNN, Ubuntu is not Incompatible please check REFERENCE OF NVIDIA-DOCKER
# REFERENCE OF NVIDIA-DOCKER 
# https://hub.docker.com/r/nvidia/cuda/

# Global arguments registry & additional package
ARG ADDITIONAL_PACKAGE
ARG REGISTRY
ARG PYTHON_VERSION

# Global arguments for Watcher
ARG GRPC_PYTHON_VERSION=1.4.0
ARG WATCHER_VERSION=0.1.0

ARG handler_file=handler.py
ARG handler_name=Handler
ARG handler_dir=/dcf/handler
ARG handler_file_path=${handler_dir}/src/${handler_file}

# Global arguments for Nvidia-docker
ARG CUDA_VERSION=10.0
ARG CUDNN_VERSION=7
ARG UBUNTU_VERSION=16.04

# ARG variable was changed after passing `FROM`
# So, it need copy other ARG variable
ARG CUDA_VERSION_BACKUP=${CUDA_VERSION}

# == MutiStage Build ==
# 1-Stage
# Get watcher - if watcher is uploaded on github, remove this line.
FROM ${REGISTRY}/watcher:${WATCHER_VERSION}-python3 as watcher

# Arguments for Watcher
ARG GRPC_PYTHON_VERSION
ARG handler_dir
ARG handler_file
ARG handler_name
ARG handler_file_path

# Watcher Setting
RUN mkdir -p ${handler_dir}
WORKDIR ${handler_dir}
COPY . .
RUN touch ${handler_dir}/src/__init__.py && \
    cp -r /dcf/watcher/* ${handler_dir}

# 2-Stage
FROM nvidia/cuda:${CUDA_VERSION}-cudnn${CUDNN_VERSION}-devel-ubuntu${UBUNTU_VERSION}

# Arguments for Nvidia-Docker
ARG CUDA_VERSION
ARG CUDNN_VERSION
ARG CUDA_VERSION_BACKUP

#RUN sed -i 's/archive.ubuntu.com/kr.archive.ubuntu.com/g' /etc/apt/sources.list
# change mirrors in ubuntu server: us to korea
RUN sed -i 's/security.ubuntu.com/ftp.daum.net/g' /etc/apt/sources.list && \
    sed -i 's/us.archive.ubuntu.com/ftp.daum.net/g' /etc/apt/sources.list && \
    sed -i 's/archive.ubuntu.com/ftp.daum.net/g' /etc/apt/sources.list

RUN apt-get update && apt-get install -y --no-install-recommends \
	build-essential \
	wget \
	tar \
	libgomp1 \
        python-setuptools \
        libgtk2.0-dev \
        python${PYTHON_VERSION} \
        python3-dev \
        python3-numpy \
        python3-pip \
        python3-tk \
        cmake \
        unzip \
        pkg-config \
        git \
        wget \
        g++ \
        make \
        automake \
        autoconf \
        bzip2 \
        libtool \
        subversion \
        libatlas3-base \
        zlib1g-dev \
        sox \
        gfortran \
        software-properties-common \
	${ADDITIONAL_PACKAGE} \
    && rm -rf /var/lib/apt/lists/* \
    && add-apt-repository ppa:deadsnakes/ppa \
    && apt-get update && apt-get install -y --no-install-recommends \
	python2.7 \
    python3.7


ENV LD_LIBRARY_PATH /usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH

# cloning kaldi source in /kaldi folder
RUN git clone https://github.com/kaldi-asr/kaldi

# following kaldi/INSTALL instructions to build kaldi

WORKDIR /kaldi/tools
RUN wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB \
    && apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2019.PUB \
    && sh -c 'echo deb https://apt.repos.intel.com/mkl all main > /etc/apt/sources.list.d/intel-mkl.list' \
    && apt-get update \
    && apt-get install -f --allow-downgrades --allow-remove-essential --allow-change-held-packages -y intel-mkl-64bit-2019.1-053

RUN extras/check_dependencies.sh && \
	make -j 13 && \
	extras/install_irstlm.sh

WORKDIR /kaldi/src
RUN ./configure --shared && \
	make depend -j 13 && \
	make -j 13

WORKDIR /
RUN pip3 install --default-timeout=500 --upgrade pip==9.0.3 &&\
    pip3 install --default-timeout=500 setuptools && \
    pip3 install --default-timeout=500 virtualenv
COPY backup/craftkim_venv /craftkim_venv
RUN virtualenv -p python2.7 /craftkim_venv/tf_cpu && virtualenv -p python2.7 /craftkim_venv/tf_gpu && virtualenv -p python3.7 /craftkim_venv/py3.7_tf_gpu

COPY SpeakerRecogv2 /SpeakerRecogv2
COPY data /data

WORKDIR /SpeakerRecogv2/online
RUN ./configure.sh

WORKDIR /

# Copy Watcher
ARG GRPC_PYTHON_VERSION
ARG handler_dir
ARG handler_file
ARG handler_name
ARG handler_file_path

ENV HANDLER_DIR=${handler_dir}
ENV HANDLER_FILE=${handler_file_path}
ENV HANDLER_NAME=${handler_name}

RUN mkdir -p ${HANDLER_DIR}
WORKDIR ${HANDLER_DIR}
COPY . .
COPY --from=0 ${HANDLER_DIR} .

RUN pip3 install --default-timeout=500 --upgrade pip==9.0.3 &&\
    pip3 install --default-timeout=500 setuptools && \
    pip3 install --default-timeout=500 grpcio==${GRPC_PYTHON_VERSION} grpcio-tools==${GRPC_PYTHON_VERSION} && \
    pip3 install --default-timeout=500 -r requirements.txt

HEALTHCHECK --interval=1s CMD [ -e /tmp/.lock ] || exit 1

ENTRYPOINT ["python3"]
CMD ["server.py"]
